### ISSUE TITLE
Architecture diagram is not showing in Perspective UI

### ISSUE THREAD

**Issue by tamaldatta91** [awslabs/aws-perspective#105]
Hello,

After scanning the resources, when an individual resource is clicked the diagram is flashing in the screen and vanished.

Thanks.

**Comment by svozza** [comment]
Do you have any filters enabled? This sounds similar to an issue here: https://github.com/awslabs/aws-perspective/issues/46. There will be a fix in the uocoming v1.1.0 release.

**Comment by itsgsurya** [comment]
Do we have any info about  v1.1.0  timelines?

**Comment by tamaldatta91** [comment]
Yes filters are enabled for few resources. After removing the filters, it seems working now.

**Comment by svozza** [comment]
Thank you, as I said this will be fixed in the new release, which should be released this month. I'm going to close this for now as we're tracking this bug in #46. If you look in the staged column of our public roadmap you can see what fixes are due to be fixed:

https://github.com/awslabs/aws-perspective/projects/2
