### ISSUE TITLE
Blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by jeff-s-burns** [awslabs/aws-perspective#126]
Unable to load resources/objects.  Message observed in Chrome toolbox console: "Access to XMLHttpRequest at 'https://... from origin 'https://...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.". Also experience error in browser "! We could not load resource configuration. Refresh page and try again. See GitHub.com for help resolving the issue"

**To Reproduce**

1. Login into application, set filter to 1 account (or more)
2. Select a resource (i.e. EC2 instance)

**Expected behavior**
Expect the EC2 instance to appear in the architecture diagram.

**Screenshots**

**Browser (please complete the following information):**

- Name:  Google Chrome Version 89.0.4389.82 (Official Build) (x86_64)

**Additional context**
We have 16 AWS accounts in our LZ but only loaded/imported 3.  We had 5 imported and removed 2 while diagnosing this problem.

**Comment by thebutler12** [comment]
Hi Jeff, the CORS message may be a red herring. Could you please have a look at the CloudWatch logs for the Lambda function called `GremlinFunction` and let us know if there are any errors in there?

**Comment by svozza** [comment]
Hey there apologies for the delay, those vertex errors in the Gremlin logs look odd to me. I'm wondering if somehow the DB has got corrupted. I can give you the instructions to wipe down the DB and let it start from scratch, it will all be back up to date within 15 minutes after the discovery task runs again. In order to do this, follow these steps:

1. Go to  `ECS->Clusters->aws-perspective-<account-number>-cluster->Scheduled Task` and click on `aws-perspective-<account-number>-rule`.
2. Click on `Edit` and set and uncheck the `Schedule rule enabled` checkbox.
3. Go to `    Lambda->Functions->aws-perspective-<account-no>-GremlinFunction-*`
4. Click on the `Test` tab and paste the following into the textbox:
```json
{
  "body": "{ \"command\": \"deleteAllNodes\" }"
}
```
5. Click the `Invoke` button.
6. Click on `Lambda->Functions->aws-perspective-<account-number>-ElasticsearchFunction-*`
7. Click on the `Test` tab and paste the following into the textbox:
```json
{
  "body": "{\"command\": \"deleteIndex\"}"
}
```
8. Click the `Invoke` button.
9. Follow step 1 to re-enable the discovery process and on the next run it will repopulate the DB.

**Comment by jeff-s-burns** [comment]
I was unable to wipe down the database. I decided to remove Perspectives and re-install.  Works now :). Except DrawIO, which I will open an issue.

**Comment by jeff-s-burns** [comment]
Closing as I have removed the installation and started new.
