### ISSUE TITLE
Support for us-west-1, US West (N. California)

### ISSUE THREAD

**Issue by egauk** [awslabs/aws-perspective#69]
According to the documentation the us-west-1 region is not supported as a deployment region.
https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-c-supported-deployment-regions.html

1. This seems strange and a possible issue with the documentation
2. Is the documentation referring to the initial deployment of perspective or the discovery deployment? In our environment discovery seems to be working fine for us-west-1

**Comment by egauk** [comment]
I see that us-west-1 does not support Cognito, not a bug...

**Comment by svozza** [comment]
Yes, when implementation guide says 'deployment regions' it's referring to the region you install the nested stacks with Gremlin, Elasticsearch etc in them and the reason `us-west-1` is not listed there is because Cognito is not available there. For importing accounts, you can import any region that has support for AWS Config.

**Comment by svozza** [comment]
We replied at the same time!
